_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 19
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 128
device:
    value: cpu
learning_rate:
    value: 0.001
num_boxes:
    value: 50
num_classes:
    value: 23
num_epochs:
    value: 50
